### PR TITLE
Show the weather icon based on local daytime

### PR DESCRIPTION
**Pull request by trap000d**
As OpenWeatherMap API doesn't care of local time and giving the icon ID for UTC time, it looks a bit inconvenient for e.g. GMT+12 local time. The idea is to check local time, compare it with sunrise and sunset times and assign icon in accordance with the local time

### CODE REVIEW

**Comment by copycat-killer** [comment]
You are comparing your localtime with `sunrise` and `sunset` from OWM, which are in UTC.

The correct way should be to get your localtime, convert it in UTC, and then do the check.

This requires another input parameter.

**Comment by copycat-killer** [comment]
As for the current weather description in the notification: you can have it in the text widget, and if you don't want to, the popup has the icon.

**Comment by copycat-killer** [comment]
Check ef872db.

**Comment by trap000d** [comment]
Well, utc parameter doesn't working as expected. For example, request to owm returns following values for my location (id=2179537):
"sunrise":1464464123 (Sun May 29 07:35:23 NZST 2016)
"sunset":1464498071 (Sun May 29 17:01:11 NZST 2016)
"dt":1464557400 (Mon May 30 09:30:00 NZST 2016)

current time via os.time()
1464560150 (Mon May 30 10:15:50 NZST 2016)
This is understandable - for owm it's still Sunday evening so it returns all times for Sunday. As for my location, the only way to get in range between sunrise and sunset right now is substract 24 hours from current local time. OK. Set utc=24. [CtrlMod4R] Everything seems working now. But.... Let's wait a couple of hours (UTC midnight).... [I'll be back]

**Comment by trap000d** [comment]
OK, I'm back. And there's a half past midnight for OWM at local time ~12:30.
"sunrise":1464550527 (Mon May 30 07:35:27 NZST 2016)
"sunset":1464584468 (Mon May 30 17:01:08 NZST 2016)
"dt":1464564600 (Mon May 30 11:30:00 NZST 2016)
os.time() - 1464568055 (Mon May 30 12:27:35 NZST 2016)

You can see that when the new day is came at OWM server it returns sunrise and sunset times for current date (not for yesterday), and now we shouldn't subtract 24 hours from current time to fit in range between sunrise and sunset. https://github.com/trap000d/lain/commit/321274e33237aefa896eabcf6fb0b2c439cd2bdb#commitcomment-17661158

P.S. And utc variable became absolutely useless

**Comment by trap000d** [comment]
From other side of the world (just in case if there are any awesome wm users living here: id=4035715)
"dt": "1464573600" (Mon May 30 14:00:00 NZST 2016)
"sunrise": "1464628126" (Tue May 31 05:08:46 NZST 2016)
"sunset": "1464667479" (Tue May 31 16:04:39 NZST 2016)
"icon":"03n"
As you can see, there is daytime now at Rarotonga, however OWM returns a night icon.

**Comment by copycat-killer** [comment]
My fault, it doesn't work because we refer to UTC, not localtime. We have to do the exact opposite. 

```lua
now     = os.time()
sunrise = tonumber(weather_now["sys"]["sunrise"]) + (utc * 3600)
sunset  = tonumber(weather_now["sys"]["sunset"]) + (utc * 3600)
icon    = weather_now["weather"][1]["icon"]

if sunrise <= now and now <= sunset then
    icon = string.gsub(icon, "n", "d")
else
    icon = string.gsub(icon, "d", "n")
end
```
Try latest commit, and set `utc=12`.

**Comment by trap000d** [comment]
Hi, It didn't work either. We were both wrong with time calculations. Here https://github.com/trap000d/lain/commit/40d3c9e33af88711c78b50b5eb3d2d48388f796e should work for any timezone (sorry again for dirty style, I'm not familiar with Lua at all).
In short words: for positive timezone we check if local time is after GMT midnight. If yes then we should subtract 24 hours from current time. For negative timezones - overturn the procedure - if the local time is before GMT midnight it means that the new day in London is appeared, so we have to add 24 hours to our local time to get into range.

**Comment by copycat-killer** [comment]
It doesn't work for me. I am in UTC+2, and your patch gives me a night icon, while now it's 09.00AM:

```
now = os.time() - (utc * 3600))

sunrise  : 1464665634 lesser than
now      : 1464671374 lesser than
sunset   : 1464719283

midnight : 1464465280 lesser than
now      : 1464671374

utc > 0 and now >= midnight, so newnow = utc + 86400 = 1464757774, but

sunrise  : 1464665634 lesser than
sunset   : 1464719283 lesser than
newnow   : 1464757774
```

Again, try latest commit:

```lua
function weather.update()
	local cmd = string.format(current_call, city_id, units, lang, APPID)
	async.request(cmd, function(f)
		local pos, err, icon
		weather_now, pos, err = json.decode(f, 1, nil)

		if not err and weather_now and tonumber(weather_now["cod"]) == 200 then
			-- weather icon based on localtime
			local now     = os.time()
			local sunrise = tonumber(weather_now["sys"]["sunrise"])
			local sunset  = tonumber(weather_now["sys"]["sunset"])
			local icon    = weather_now["weather"][1]["icon"]
			local utc_m   = string.gsub(read_pipe(string.format("date -u -d 'today 00:00:00' +'%%s'")), "\n", "")

			if now > tonumber(utc_m) then
				now = now - (utc * 3600)
			end
			
			if sunrise <= now and now <= sunset then
				icon = string.gsub(icon, "n", "d")
			else
				icon = string.gsub(icon, "d", "n")
			end

			weather.icon_path = icons_path .. icon .. ".png"

			widget = weather.widget
			settings()
		else
			weather.icon_path = icons_path .. "na.png"
			weather.widget:set_markup(weather_na_markup)
		end

		weather.icon:set_image(weather.icon_path)
	end)
end
```

**Comment by trap000d** [comment]
I think I've figured out how to operate with it. The only two factors which actually matter are 
1) the relative position of local midnight and UTC midnight and
2) timezone sign (+ or -). 
https://github.com/trap000d/lain/commit/0493baffd5f17b6331974ae1dac4d404d016e351

I'd renamed utc variable to something like "tz_offset" (as utc means "Coordinated Universal Time" it could confuse the user). 

Also there is a way to automatically calculate tz offset without defining it as argument:
```
local function get_timezone()
  local now = os.time()
  return os.difftime(now, os.time(os.date("!*t", now)))
end
tz_offset = get_timezone()
```
When I inserted it into script, it worked for me for a while but after some time has began to throw error at the line `return os.difftime(now, os.time(os.date("!*t", now)))`:
.......... weather.lua:127: attempt to call field 'date' (a nil value)
The possible case is explained here http://lua-users.org/lists/lua-l/2010-09/msg00209.html

P.S. Time is complex :)

**Comment by copycat-killer** [comment]
I did a clean up and solved the `os.date` error.

Check 1635e0a.

**Comment by trap000d** [comment]
Awesome, it works!!! It complains for 
```
attempt to perform arithmetic on field 'isdst' (a boolean value)
```
but this patch fixes it
```lua
return os.difftime(now, os.time(os.date("!*t", now))) + ((os.date("*t").isdst and 1 or 0) * 3600)
```

**Comment by copycat-killer** [comment]
Patched. Let me know if anything goes wrong.

**Comment by trap000d** [comment]
It seems everything working good. Thank you.

**Pull request closed without merging**
