### PR TITLE
alsabar notification with user-defined parameters 

### PR DESCRIPTION
**Pull request by kps65**
Provides user with a possibility to change notification preset and volume bar parameters without patching library code. For example, my parameters:
```lua
alsabar.notifications.preset = {
	timeout = 2,
	screen = awful.tag.getscreen(awful.tag.selected()),
	position = "bottom_right",
	font = beautiful.monofont or 'Droid Sans Mono 8',
	fg = beautiful.fg_widget,
	bg = beautiful.bg_focus,
	run = naughty.destroy(self),
}
alsabar.notifications.bar = {
	size = 25,
	fill = "█",
	empty = "░",
}
```

The changes seem to be safe (tested on my awesome config).

### CODE REVIEW

**Comment by copycat-killer** [comment]
Please provide a wiki extension and default parameters for those who don't want customizations.

**Comment by kps65** [comment]
Well, I'll do that. Please, give me a clue concerning a right way to edit wiki. I cannot find a way to make pull request for wiki submodule. Should I clone it with git and provide a branch or may I edit your copy of wiki directly?

BTW, description of bar_size parameter in the wiki seems to be obsolete, so I'd correct that. 
Default parameters are unchanged and initialization of alsabar.notification is not required in user code. So, nothing changed for users of the previous version.

**Comment by copycat-killer** [comment]
Something is changed for me though: I had no issues testing your branch, but also no bar (I'm using standard copland theme).

To edit the wiki, you should clone it as subrepository first.

**Comment by copycat-killer** [comment]
Wait!

(*Too much work lately...*)

You can already do at least 85% of this commit. Just pass your custom `notifications` table [like this](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.holo#L237-252).

But I spotted something fancy in your pull. You can add your new stuff without changing the original preconditions.

**Comment by kps65** [comment]
On Mon, 09 Mar 2015 11:28:45 -0700
Luke Bonham <notifications@github.com> wrote:

k> Something is changed for me though: I had no issues testing your branch, but also no bar (I'm using standard copland theme).

I use slightly customized zenburn, but I'll look into copland.

Right now I see possible problem with font declaration.
There is no separate font and font_size declarations in naughty.notify.
My fault, sorry. I'll correct that.

k> To edit the wiki, you should clone it as subrepository first.

Yes, I've initialized wiki submodule in my local copy.

**Comment by kps65** [comment]
On Mon, 09 Mar 2015 11:39:30 -0700
Luke Bonham <notifications@github.com> wrote:

k> Wait!
k> 
k> (*Too much work lately...*)
k> 
k> You can already do at least 85% of this commit. Just pass your custom `notifications` table [like this](https://github.com/copycat-killer/awesome-copycats/blob/master/rc.lua.holo#L237-252).
k> 
k> But I spotted something fancy in your pull. You can add your new stuff without changing the original preconditions.

Yes, seems to be the best way. I'll work at it.

**Comment by copycat-killer** [comment]
I'll close this to make you do a new clean request.

**Comment by kps65** [comment]
Dear Luke,

I've redesigned the code to keep all the previous notification parameters
working. notifications.preset now takes precedence, if defined, and the
previous parameters actually store default values for it. User-defined
previous parameters also work in my configuration.

I've tested the code with copland theme, it works on my machine.

I've also edited alsabar.md in wiki, but I do not know the right way to
commit it to github, because git submodule is a clone of your repository,
not my fork. Sorry for inconvinience, but I'm not experienced with
git submodules yet.

Please, take a look at the code and wiki files attached. If it's acceptable
for you, I'll do a pull request.

Regards,

Konstantin

On Mon, 09 Mar 2015 11:53:58 -0700
Luke Bonham <notifications@github.com> wrote:

k> I'll close this to make you do a new clean request.
k> 
k> ---
k> Reply to this email directly or view it on GitHub:
k> https://github.com/copycat-killer/lain/pull/101#issuecomment-77918259

**Comment by copycat-killer** [comment]
Great, but... I can't find attachments. :D

**Comment by kps65** [comment]
Hmmm... I have them here in outgoing message. 
It seems than github cuts them off.
Is it possible to send you email directly?

On Tue, 10 Mar 2015 10:45:09 -0700
Luke Bonham <notifications@github.com> wrote:

k> Great, but... I can't find attachments. :D
k> 
k> 
k> On 10 Mar 15 ◦ 07:54, Konstantin wrote:
k> > Dear Luke,
k> > 
k> > I've redesigned the code to keep all the previous notification parameters
k> > working. notifications.preset now takes precedence, if defined, and the
k> > previous parameters actually store default values for it. User-defined
k> > previous parameters also work in my configuration.
k> > 
k> > I've tested the code with copland theme, it works on my machine.
k> > 
k> > I've also edited alsabar.md in wiki, but I do not know the right way to
k> > commit it to github, because git submodule is a clone of your repository,
k> > not my fork. Sorry for inconvinience, but I'm not experienced with
k> > git submodules yet.
k> > 
k> > Please, take a look at the code and wiki files attached. If it's acceptable
k> > for you, I'll do a pull request.
k> > 
k> > Regards,
k> > 
k> > Konstantin
k> > 
k> > On Mon, 09 Mar 2015 11:53:58 -0700
k> > Luke Bonham <notifications@github.com> wrote:
k> > 
k> > k> I'll close this to make you do a new clean request.
k> > k> 
k> > k> ---
k> > k> Reply to this email directly or view it on GitHub:
k> > k> https://github.com/copycat-killer/lain/pull/101#issuecomment-77918259
k> > 
k> > ---
k> > Reply to this email directly or view it on GitHub:
k> > https://github.com/copycat-killer/lain/pull/101#issuecomment-78070392
k> 
k> 
k> ---
k> Reply to this email directly or view it on GitHub:
k> https://github.com/copycat-killer/lain/pull/101#issuecomment-78107768

**Comment by copycat-killer** [comment]
Of course, you can find my mail in the readme.

**Pull request closed without merging**
