### PR TITLE
Add the new function: pulseaudio (with sink autodetect)

### PR DESCRIPTION
**Pull request by MaksVal**
The new widget: pulseaudio

Hi! Thanks for your work!
I added the new widget for pulseaudio... Are you interesting in my changes?

### CODE REVIEW

**Comment by copycat-killer** [comment]
Sure, but I need two things:

1. move it to `contrib`
2. a wiki entry

**Comment by MaksVal** [comment]
Hi!
Do you can check my changes?
1. Fix
2. Fix(sorry. I added to your wiki)

**Comment by copycat-killer** [comment]
It's a bit messy, you got it wrong with the wiki.

I'll do it for you, but I have to reject this pull first. Don't worry, your work will be included anyway.

**Comment by MaksVal** [comment]
Thaks! Sorry, I am a beginner in this service

**Pull request closed without merging**
