### PR TITLE
#177 bat.lua fix

### PR DESCRIPTION
**Pull request by andering**
It's my fir pull so be merciful with me :).
Looks like mess because i use tabulators not spaces. What should i do with that ?

### CODE REVIEW

**Comment by andering** [comment]
Ok now i can see what happends when all those >0 conditions are not there.
When i unplug and plug battery charger power_now is for moment at 0, so in
`rate_time = (energy_full - energy_now) / rate_power or rate_current`
we have division by 0 so infinite time for charging.

But to just limit output time between 0 - 23 is just doesn't seems right.
First i would get rid of division by 0 or maybe skip the round or signalize ?

**Comment by copycat-killer** [comment]
> First i would get rid of division by 0 or maybe skip the round?

Timeout is 30 seconds, so we can just skip the rest of the function if rate_power is zero.

**Comment by andering** [comment]
```
-- if rate = 0 or rate not defined skip the round
if not (rate_power and rate_power > 0) and 
	not (rate_current and  rate_current > 0) 
then
	return 
end
```

So while im newbie in lua i hope simple return is fine. Tested on my Desktop and works fine.

**Comment by andering** [comment]
So, now should be ok.

```
-- if rate = 0 or rate not defined skip the round
if 	not (rate_power and rate_power > 0) and 
	not (rate_current and  rate_current > 0) and
	not bat_now.status == "Full"
then
	return 
end
```

**Comment by copycat-killer** [comment]
Seems ok to me too. Thanks for the work.

**Pull request merged**
