### PR TITLE
Countdown widget.

### PR DESCRIPTION
**Pull request by geripgeri**
Hi,
I created a universal countdown widget, example usage: Tea timer.
Hope you like it :)

Example lua script: https://github.com/geripgeri/lain/wiki/Contributed-Widgets#countdown-widget-with-icon--notification-example

### CODE REVIEW

**Comment by copycat-killer** [comment]
There are some points:

1. there are likely changes to be made in your code, due to the new API, read [here](https://github.com/copycat-killer/lain/issues/248);
2. I don't like the polling, you could just use awesome signals and timers;
3. most probably, you can do all of this with `abase` template.

**Comment by copycat-killer** [comment]
What you want is not a widget, but a timer feeding a widget. There's no need for a new lain widget, you can just use awesome signals and timers, like said above. Add this in the widget section of your `rc.lua`:

```lua
local countdown = {
    widget = wibox.widget.textbox(),
    icon   = wibox.widget.imagebox(beautiful.countdown_normal),
}

function countdown.set()
    awful.prompt.run {
        prompt       = "Countdown minutes: ",
        textbox      = awful.screen.focused().mypromptbox.widget,
        exe_callback = function(timeout)
            countdown.seconds = tonumber(timeout)
            if not countdown.seconds then return end
            countdown.seconds = countdown.seconds * 60
            countdown.icon:set_image(beautiful.countdown_normal)
            countdown.widget:set_markup(string.format("%d minutes remaining", timeout))
            countdown.timer = gears.timer({ timeout = 1 })
            countdown.timer:connect_signal("timeout", function()
                if countdown.seconds > 0 then 
                    local minutes = math.floor(countdown.seconds / 60)
                    local seconds = math.fmod(countdown.seconds, 60)
                    if minutes > 0 then
                        if seconds > 0 then
                            countdown.widget:set_markup(string.format("%d minutes and %d seconds remaining", minutes, seconds))
                        else
                            countdown.widget:set_markup(string.format("%d minutes remaining", minutes))
                        end
                    else
                        countdown.widget:set_markup(string.format("%d seconds remaining", seconds))
                    end
                    countdown.seconds = countdown.seconds - 1
                else
                    naughty.notify({
                        title = "Countdown widget",
                        text  = string.format("%s minutes timeout!", timeout)
                    })
                    countdown.icon:set_image(beautiful.countdown_up)
                    countdown.widget:set_markup("Time is up")
                    countdown.timer:stop()
                    countdown.timer_sec:stop()
                end
            end)
            countdown.timer:start()
        end
    }
end

countdown.icon:buttons(awful.util.table.join(
    -- left click
    awful.button({}, 1, function() countdown.set() end),
    -- right click
    awful.button({}, 3, function()
        if countdown.timer.started then
            countdown.timer:stop()
            countdown.widget:set_markup("")
            countdown.icon:set_image(beautiful.countdown_normal),
            naughty.notify({
                title = "Countdown widget",
                text  = string.format("Timer stopped", timeout, t)
            })
        end
    end)
))
```

Then, add `countdown.widget` and `countdown.icon` to your favourite wibox. Also, set `countdown_normal` and `countdown_up` in your `theme.lua` to the respective icons path (strings).

**Be aware that** this code is only compatible with Awesome >= 4.0.

**Comment by geripgeri** [comment]
Thanks

**Comment by copycat-killer** [comment]
Even better, instead of icons, you can use a [checkbox](https://awesomewm.org/doc/api/classes/wibox.widget.checkbox.html).

```lua
local countdown = {
    widget   = wibox.widget.textbox(),
    checkbox = wibox.widget {
        checked      = false,
        check_color  = beautiful.fg_focus,  -- customize
        border_color = beautiful.fg_normal, -- customize
        border_width = 2,                   -- customize
        shape        = gears.shape.circle,
        widget       = wibox.widget.checkbox
    }
}

function countdown.set()
    awful.prompt.run {
        prompt       = "Countdown minutes: ", -- floats accepted
        textbox      = awful.screen.focused().mypromptbox.widget,
        exe_callback = function(timeout)
            countdown.seconds = tonumber(timeout)
            if not countdown.seconds then return end
            countdown.checkbox.checked = false
            countdown.minute_t = countdown.seconds > 1 and "minutes"  or "minute"
            countdown.seconds = countdown.seconds-- * 60
            countdown.timer = gears.timer({ timeout = 1 })
            countdown.timer:connect_signal("timeout", function()
                if countdown.seconds > 0 then
                    local minutes = math.floor(countdown.seconds / 60)
                    local seconds = math.fmod(countdown.seconds, 60)
                    countdown.widget:set_markup(string.format("%d:%02d", minutes, seconds))
                    countdown.seconds = countdown.seconds - 1
                else
                    naughty.notify({
                        title = "Countdown",
                        text  = string.format("%s %s timeout", timeout, countdown.minute_t)
                    })
                    countdown.widget:set_markup("")
                    countdown.checkbox.checked = true
                    countdown.timer:stop()
                    countdown.timer_sec:stop()
                end
            end)
            countdown.timer:start()
        end
    }
end

countdown.checkbox:buttons(awful.util.table.join(
    -- left click
    awful.button({}, 1, function() countdown.set() end),
    -- right click
    awful.button({}, 3, function()
        if countdown.timer and countdown.timer.started then
            countdown.timer:stop()
            countdown.checkbox.checked = false
            countdown.widget:set_markup("")
            naughty.notify({
                title = "Countdown",
                text  = "Timer stopped"
            })
        end
    end)
))
```
Add `countdown.checkbox` instead of `countdown.icon` in your wibox.

**Pull request closed without merging**
