### PR TITLE
Battery percentage going above 100% fix

### PR DESCRIPTION
**Pull request by aajjbb**
Hi,

This is a small patch to not allow battery percentage go above 100% as mentioned by @JJK96 in [issue](https://github.com/copycat-killer/lain/issues/158)

### CODE REVIEW

**Comment by JJK96** [comment]
Asuming that your patch works (haven't tested it yet) the if then else statement that is around your code is useless then, maybe remove it?

**Comment by aajjbb** [comment]
Actually I just realized I haven't done nothing useful here. I haven't paid attention to the other ifs in the block. Actually I supposed the issue is due to an rounding problem with the division. I don't know lua well enough to assure whether this is the issue, but it's the most probable one.

Please, ignore my silly patch.

**Comment by JJK96** [comment]
I will try to debug it tomorrow, will post a patch if i found a fix

**Comment by aajjbb** [comment]
I think I've found the real source of the issue. I'll post a patch soon.

**Pull request closed without merging**
