### PR TITLE
Add behaviour to show notification windows on same screen as widget

### PR DESCRIPTION
**Pull request by Unode**
Feature discussed in #125

### CODE REVIEW

**Comment by Unode** [comment]
The pull request also includes a fix for the usage of the `src_pos` argument.
It was incorrectly passed and always ended up as `nil` and then set to default `1`.

**Comment by Unode** [comment]
Wiki updated as per pull-request.

**Comment by aajjbb** [comment]
Great job.

**Comment by copycat-killer** [comment]
I don't understand the need for this.

If you want the `followmouse` behaviour, just set `screen/scr_pos = mouse.screen`.

And about `scr_pos`: `calendar:show` has [`scr` as argument](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L33), which is [correctly passed](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L119) for mouse hovering signal, and which can be optionally defined by user.

**Comment by copycat-killer** [comment]
The only thing I'm agree with is updating `show` in supported widgets, in order to define which `screen` to be show in.

**Comment by Unode** [comment]
Where would I set `screen = mouse.screen`? If it's in the widget initialization code, I tired it and it didn't work. It's the only part I can control from `awesome/rc.lua`.
The reference to `mouse.screen` must exist inside the `show` functions of the widget. `mouse.screen` is an integer, doing `screen = mouse.screen` will store whatever value was present at the time of evaluation. It won't update in the future, i.e. not a reference, so it won't actually follow the mouse.

The extra parameter was to maintain backwards compatibility. Not my call to break it.

As for `scr` being correctly passed, the scope is wrong. [`calendar.scr_pos`](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L114)  holds the value, not [`src_pos`](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L119). As it is, the calls to [`show`](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L119) only pass `nil`. Confirmed by printing `scr` inside the function.
Also, you are setting the default value of `src_pos` twice. Once in [`calendar.worker`](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L114) and again in [`calendar.show`](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L99) (the `or 1` part). If you drop [this one](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L99) you'll see the `nil`.

**Comment by copycat-killer** [comment]
Ok, I understood now. But since you didn't update all the required widgets and there are now conflicts with this branch, I'll do the required changes.

By the way,

> Where would I set `screen = mouse.screen`? If it's in the widget initialization code, I tired it and it didn't work. It's the only part I can control from `awesome/rc.lua`.

Minimal working examples:

```lua
lain.widgets.calendar.attach(mytextclock, {scr_pos = mouse.screen})

myfs = lain.widgets.fs({
    notification_preset.screen = mouse.screen
})

myweather = lain.widgets.weather({
    city_id  = 1234567, --placeholder
    notification_preset = { screen = mouse.screen }
})
```

**Comment by copycat-killer** [comment]
Done. Please take a look at e5e199c and see if everything is ok.

Notice that now `fs` has `notification_preset` as entry (no more global), and `args.w_notification_preset` is now `args.notification_preset` in `weather`.

**Comment by Unode** [comment]
Hi Luke,

The examples you mentioned didn't work for me:
```
myfs = lain.widgets.fs({
    notification_preset.screen = mouse.screen
})
```
gives me a syntax error.

and the calendar one. Should it be `calendar:attach` no? With `calendar.attach` I get some nil reference inside the function.

Regardless, https://github.com/copycat-killer/lain/commit/e5e199c1488cd33b96e15f9879a4b9abcfdcc572 seems to be missing something.
The quick test I did resulted in calendar only showing up on the first screen. I'll do better tests later.
The fs widget displays on the correct screen but now the notification window doesn't vanish when unhovered. I need to click it to go away.

**Comment by copycat-killer** [comment]
> The examples you mentioned didn't work for me

Sorry, I was in a hurry. Correct version:

```lua
myfs = lain.widgets.fs({
    notification_preset = { screen = mouse.screen }
})
```

and yes, it was `calendar:attach`. Just a typo.

> The quick test I did resulted in calendar only showing up on the first screen. 

Did you try this?

```lua
lain.widgets.calendar:attach(mytextclock, { followmouse = true })
```

> The fs widget displays on the correct screen but now the notification window doesn't vanish when unhovered. I need to click it to go away.

Another typo. Fixed.

**Comment by Unode** [comment]
Ok, with the last fix the fs widget now works fine.

The calendar not yet. Still always shows on screen 1. Regardless of the position of the mouse. Using:
```
lain.widgets.calendar:attach(mytextclock, { fg = theme.fg_focus,
                                            font = theme.font_name,
                                            font_size = theme.font_size,
                                            followmouse = true })

```
Inspecting the code I think I found the issue.
The `local` keyword [here](https://github.com/copycat-killer/lain/blob/master/widgets/calendar.lua#L94) causes `scrp` to be `nil` after the end of the if clause.

**Comment by copycat-killer** [comment]
I'm doing my worst lately.

Removed `local`. Tell me now.

**Comment by Unode** [comment]
All good now.

Thanks and sorry for the trouble.

**Comment by copycat-killer** [comment]
No, thanks to you for enhancing my work.

**Pull request closed without merging**
