### PR TITLE
allow add_us_secondary to be turned off.

### PR DESCRIPTION
**Pull request by stwa**
problem with test expression and nil value.

### CODE REVIEW

**Comment by copycat-killer** [comment]
Why don't you pass `add_us_secondary = false` instead?

**Comment by stwa** [comment]
Because it is not working, Lua is acting strange in this case.

Look at this example:
> print( 3>1 and 1 or "False" )        -- works
1
> print( 3>1 and false or "oops" )     -- failed, should return false
oops
> print( 3>1 and nil or "oops" )       -- failed, should return nil
oops

Example from here:
http://lua-users.org/wiki/ExpressionsTutorial

**Comment by copycat-killer** [comment]
OK, I tried the widget and the problem is indeed present.

Anyway, that example is correct. Lua always returns the non boolean value, if it's not `nil`, and `nil` is interpreted as `false`.

So, in the second instance, you have `3>1 and false` which is `T and F = F`, so the result is `F or string`, which is converted to `nil or string` and returns `string`. The same applies for the third one.

**Comment by stwa** [comment]
Thank you for your explanation, makes a lot more sense now!

Am 24. September 2015 11:51:04 MESZ, schrieb Luke Bonham <notifications@github.com>:
>OK, I tried the widget and the problem is indeed present.
>
>Anyway, that example is correct. Lua always returns the non boolean
>value, if it's not `nil`, and `nil` is interpreted as `false`.
>
>So, in the second instance, you have `3>1 and false` which is `T and F
>= F`, so the result is `F or string`, which is converted to `nil or
>string` and returns `string`. The same applies for the third one.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/copycat-killer/lain/pull/144#issuecomment-142877284

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Pull request merged**
