### PR TITLE
Weather widget - day/time in UTC

### PR DESCRIPTION
**Pull request by trap000d**
utc_offset option/function is not need anymore

### CODE REVIEW

**Comment by copycat-killer** [comment]
Not working for me: it gives a nightly icon, while is's AM here.

**Comment by trap000d** [comment]
Hmm, on my 3 computers it works properly. I've added some debug output: https://github.com/trap000d/lain/blob/debug/widget/weather.lua
Could you give it a try and send me output from ~ /.xsession-errors - it should look like:
```
2017-09-07 09:52:42 W: Times:1504734762 43200 1504722990 1504764132 1504699200 1504656000
2017-09-07 09:52:42 W: Weather icon:10d
```

**Comment by copycat-killer** [comment]
Maybe because your 3 computers are in the same country. 😃

I'll give you the log once I come back home.

**Comment by copycat-killer** [comment]
```shell
2017-09-07 17:51:55 W: awesome: Times:1504799515 3600 1504845358 1504891431 1504735200 1504731600
2017-09-07 17:51:55 W: awesome: Weather icon:11n
```
Icon is `n`, while it should be `d` (well, still for a few minutes since 6PM is the limit).

**Comment by trap000d** [comment]
After looking at your logs... Well... I've forgotten of DST. Also I've tried to optimize code a bit. Here the debug version. Please test if it works on your machine.
https://github.com/trap000d/lain/commit/43b91149608bdaddb7de563135dc709cdfa5951e

**Comment by copycat-killer** [comment]
It's OK now.

Remove debugs, `git rebase -i HEAD~3` to squash and `push --force` into your master, so I can merge.

**Comment by trap000d** [comment]
OK. https://github.com/copycat-killer/lain/pull/360/commits/59f99ea07bb77433a2373fb31337fbd59daaf3d9

**Comment by copycat-killer** [comment]
Thank you.

**Pull request merged**
