### PR TITLE
Allow resizing uselesstiles with the mouse. fix #48

### LINKED ISSUE #48: Useless gaps don't work with mouse resize in Awesome stable branch
in the default tiling layouts, (awesome 3.4), modkey+rmb will resize whatever client is under the cursur and slide the layout divisions around accordingly. uselesstile doesn't do this. :(

### PR DESCRIPTION
**Pull request by Ram-Z**

### CODE REVIEW

**Comment by Ram-Z** [comment]
This will work on the latest git of awesome. (going back to [8d7b0feedd](https://github.com/awesomeWM/awesome/commit/8d7b0feedd9de3cb41bcbc2deff26c9a8ab34450) at least)

I suppose you can only merge this in once a new version of awesome has been released.

**Comment by copycat-killer** [comment]
Indeed, I was waiting for the new stable.

But thanks for your work.

In the meantime, you could extend this to `uselessfair` and `uselesspiral` as well.

**Comment by Ram-Z** [comment]
On Jan 08, 2015 at 3:17, Luke Bonham wrote:
> In the meantime, you could extend this to `uselessfair` and 
> `uselesspiral` as well.
I don't have those enabled so it's not really on my priority list. But 
if I find the time, I might have a look, no promises though.

**Comment by copycat-killer** [comment]
It's ok, I'd do it anyway, once it's merged.

**Comment by cosarara97** [comment]
Hello! Ram-Z's branch stopped working with the latest awesome from git, so I ported his changes to the latest lain: https://github.com/cosarara97/lain

**Comment by copycat-killer** [comment]
Good news, but lain aims at **stable**awesome branch.

If your porting works with it, then do a pull request.

**Comment by cosarara97** [comment]
> Good news, but lain aims at stableawesome branch.
> If your porting works with it, then do a pull request.

It probably doesn't, since I replaced lots of things that are deprecated in the git version by the new stuff.

> There is useless gaps support in git branch.
> Isn't mouse resizing working with that?

Damn I had no idea. I will look at it, thanks.

**Comment by copycat-killer** [comment]
> I will look at it, thanks.

Let me know please (I am so lazy).

**Comment by cosarara97** [comment]
It works fine, yes. I'm using lain for termfair only now.

**Pull request closed without merging**
