### PR TITLE
Alsabar.lua changes

### PR DESCRIPTION
**Pull request by ProfessorOptics**
Fixed spelling heigth = height; added support for mouse buttons 1 through 5; added togglechannel as per previous version using new api; small fixes to accomodate togglechannel variable.

Also removed trailing whitespaces; added terminal variable for local use; mixer variable to store "amixer"

any issues, let me know.

### CODE REVIEW

**Comment by copycat-killer** [comment]
I decided to remove  the buttons stuff, but it seems people want them, so ok.

**Comment by copycat-killer** [comment]
Wait, no, sorry, there is a specific motivation for those changes: removing `beautiful` and external variable dependencies, and let the user decide about buttons.

The reason is portability and modularity: you'll see this applied in the next `awesome-copycats` commits.

Now `notifications` is `notification_preset`, and if you want buttons just add the snippet in your `rc.lua`.

**Comment by ProfessorOptics** [comment]
I wasn't aware of that, and now i understand why it was missing after the update. I'll keep that in mind and update my scripts accordingly.

**Comment by ProfessorOptics** [comment]
Does adding toggle channel and its various functions remove the portability? I could modify the script according to your recent changes and send another pull request?

**Comment by copycat-killer** [comment]
The point is, we don't need `togglechannel`, since `amixer` or `args.cmd` grabs it anyway.

**Comment by ProfessorOptics** [comment]
I see. Any different setups would have to set their own command. Like mine, because i have multiple devices with amixer, helper.async grabs "mute" from the last device. This poses a problem because that device doesn't mute anything.

**Comment by copycat-killer** [comment]
You're right, it's a bit inflexible like this.

I readded `togglechannel` back in 156515e.

**Pull request merged**
