### PR TITLE
only update widget text if it has changed since the last timer tick

### PR DESCRIPTION
**Pull request by everslick**
I realized that widget.set_markup() is kinda bottleneck. On my atom netbook awesome has around 8% cpu load if idle, when i set the timer to 1 second for each of my widgets. 

this patch reduces cpu load to 4-5% while still maintaining high refresh rates. fine tuning the timers reduces the cpu load further (I set them to 1 for testing the patch).

pls note, I only changed the widgets i use, the others, I cannot really test. would be nice if at least the base widget could get enhanced the same way, but i failed to make a clean implementation. my Lua skills are rather poor.

### CODE REVIEW

**Comment by copycat-killer** [comment]
Thanks for your effort, I've never thought about this, "thanks" to my fast CPUs.

I'll see if I can write an helper to automatize the check, otherwise I'll merge this and do the rest.

>Fine tuning the timers reduces the cpu load further (I set them to 1 for testing the patch).

@ff2000 Can you try this patch with fine tuning and see if it solves #114?

**Comment by everslick** [comment]
maybe a simple wrapper around set_markup() will do? my approach tries do push as much as possible into the 'if' to minimize cpu load. on the other hand we can avoid maybe even more cpu cycles on each timer tick by combining ff2000's approach with mine.

**Comment by ff2000** [comment]
I'm waiting for https://github.com/awesomeWM/awesome/pull/404 - it might be many of those performance issues could be solved by that.
I also used qtile now for some days. Though it is in development for quite some years it still lacks too many things, but does extremely well performance-wise. It idles at ~1.5% CPU usage while I use widgets (cpu, net, memory graphs) that drive awesome to >10% here. I did not have the time to look at the code too deep (and I won't have it for the next weeks/months), could be inspiring for awesome, too.
Concerning this PR: Couldn't this be done in a more generic way? Implementing cahing for every widget seems to be quite some boilerplate. Vicious IMHO does caching quite good (easy to use and generic). Talking about timers in #114 I thought this was already rejected (resetting timers for individual widgets), and I can live with it.

I will try this PR the next days. Hope that's OK.

**Comment by copycat-killer** [comment]
The new widget system looks amazing, but probably it'll take some time.

> I thought this was already rejected

No, I do want to improve performances and I'm happy you guys made me focus on it. It's just I have little time at the moment.

**Comment by copycat-killer** [comment]
I have to reject this because violates #141 solution, has conflicts with master, and does not consider all the widgets.

But don't worry, I applied the patch anyway. Check #114 thread.

**Pull request closed without merging**
