### PR TITLE
asyncshell: minor fix to spawn with shell invocation

### PR DESCRIPTION
**Pull request by setrofim**
Fixed an erroneous call to "awful.spawn.with_shell".

### CODE REVIEW

**Comment by copycat-killer** [comment]
With your pull request, then what would be the point of that if-else statement?

Which issue is causing you that if-else?

**Comment by setrofim** [comment]
When requiring tyrannical, I was getting a bunch of errors "attempt to call field 'with_shell' (a nil value)" on that line. But, yes, my fix is probably not correct; maybe the if condition needs to change

**Comment by setrofim** [comment]
tg

**Comment by setrofim** [comment]
I've updated the pull request to change the if condition instead.

**Pull request merged**
